### ISSUE TITLE
Feature request remove shaders

### ISSUE THREAD

**Issue by Neodymium5312** [nosklo/cemu_utils#1]
Request for adding of the ability to remove shaders by hash or offset to enable removing shaders with link or compile errors

**Comment by nosklo** [comment]
This is the log.txt for loading the complaining gamer's shader cache file.
[log.txt](https://github.com/nosklo/cemu_utils/files/1575159/log.txt)

**Comment by nosklo** [comment]
While inspecting the actual shader cache I can't find all those shaders in the file. I found only one of them, the 0086e7ebadb97735 shader. Removing it stops the error from showing up on log.txt so it seems to be the right track. But I can't find the other shaders with errors in the shader cache file.

**Comment by nosklo** [comment]
NoskLo - Today at 8:28 AM
I'm creating a tool to remove shaders from the shader cache based on compilation errors written to log.txt when loading the cache.  I'm parsing the log.txt for lines that match Link error in shader 0086e7ebadb97735 and trying to find that number in the cache table name1. However some of the errors don't have a corresponding key in the cache. What am I missing here? @Exzap
https://github.com/nosklo/cemu_utils/issues/1
GitHub
Feature request remove shaders · Issue #1 · nosklo/cemu_utils
Request for adding of the ability to remove shaders by hash or offset to enable removing shaders with link or compile errors

Exzap - Today at 8:43 AM
Whats the point of removing shaders with compile error? They will be added again next time Cemu encounters them in the game
NoskLo - Today at 8:44 AM
How deterministic are them? They will be added exactly the same? Last conversation I got the impression that the shader state could play a part on this, since the same shaders being added aren't binary equal
Exzap - Today at 8:45 AM
100% deterministic
I told you that the entire renderstate is dumped into the shader cache, even stuff that isn't used for shader decompilation (some of that renderstate data is almost random)(edited)
NoskLo - Today at 8:46 AM
That random part can't however be causing the compile errors. I see
Exzap - Today at 8:46 AM
Same shader will always cause a compile error
NoskLo - Today at 8:47 AM
ok, I will give up this remove error idea. Anyway, shouldn't the shaders with errors be in the cache?
Exzap - Today at 8:48 AM
Then you'd get stutter for shaders with compile errors
And there is always the chance that shader errors go away with a Cemu update
NoskLo - Today at 8:49 AM
Every time I load the cache, I get the errors. So when searching the table I should find a shader with that number... That is the part I don't understand
But it is ok. I will close the issue.
Exzap - Today at 8:50 AM
You should be able to find the shaders in transferable cache based on the name from log
NoskLo - Today at 8:50 AM
Yeah, they are not there, somehow
Exzap - Today at 8:51 AM
What game and which GPU?
NoskLo - Today at 8:51 AM
nvidia gpu, botw
the shader cache is not mine though...
Exzap - Today at 8:52 AM
Any graphic packs active? The compile errors can come from graphic pack shaders as well
NoskLo - Today at 8:53 AM
when loading my own shader cache with the same graphic packs I get no errors. The error seems to come from inside the cache... Can a shader cause error on another shader? Or they are independent?
Exzap - Today at 8:54 AM
independent
I was under the impression that all BotW shaders compile fine. My own cache has zero errors
Maybe your cache has shaders from a different game?:thinkling:
NoskLo - Today at 8:55 AM
not my cache, but maybe that is it. Even then I should be able to use the log to identify the shader and hopefully remove it? That was the initial idea
I will try to bisect the shader cache to a single shader with error
Exzap - Today at 8:56 AM
Can you PM me the full log?
NoskLo - Today at 8:56 AM
sure
rajkosto - Today at 8:56 AM
@NoskLo so you can find the shaders that have the compile errors but not the ones that have the link errors, yea ?(edited)
Exzap - Today at 8:57 AM
Internal error: assembly compile error for vertex shader
hints at driver bug(edited)
Only seen these errors on Splatoon
rajkosto - Today at 8:58 AM
what about the ones with the unknown texture variable
thats the first one he removed
NoskLo - Today at 8:59 AM
All of them say Link error, and 2 lines below assembly compile error
NoskLo - Today at 9:00 AM
I believe that it is from another game, that theory is very good. The part I don't get is the fact that I can't actually find the shader in the cache table
Exzap - Today at 9:00 AM
[15:54:01] Compile error in shader 3793ef813291202f. Log:
[15:54:01] 0(210) : error C1008: undefined variable "textureUnitPS18"
Thats the only one where there is a legitimate compile error. All others are just the driver failing.
But regardless, all of them should be in the cache
NoskLo - Today at 9:02 AM
Thanks for the insight, I will double check my code and try to bisect the shader with error to see why name1  is not matching with the number in the log
rajkosto - Today at 9:06 AM
maybe the link errors show a different hash from the compile errors ?
NoskLo - Today at 9:06 AM
How do you tell a link error from a compile error
rajkosto - Today at 9:07 AM
it says link error instead of compile error :stuck_out_tongue:
NoskLo - Today at 9:07 AM
[15:52:10] Link error in shader 0086e7ebadb97735. Log:
[15:52:10] Vertex info
-----------
Internal error: assembly compile error for vertex shader at offset 2092:
all of them are like this
rajkosto - Today at 9:07 AM
and you can find them ?
NoskLo - Today at 9:07 AM
they say Link error in first line, then compile error two lines below
I can find the first one
I have removed that shader, and the error for that one disappeared from the log next load
The other errors remain

**Comment by nosklo** [comment]
I have isolated a single shader with the problem. 

[This shader cache](https://github.com/nosklo/cemu_utils/files/1575477/dcac9927_bad_f5d76d8d8fbfa76f.zip) contains only one shader. When trying to load it I get the error below on the [log.txt](https://github.com/nosklo/cemu_utils/files/1575480/log.txt):
```
[12:13:35] Link error in shader f5d76d8d8fbfa76f. Log:
```

**Comment by nosklo** [comment]
- 153f11c13d4a304b becomes 553f11c13d4a304b, 
- 0e8c799828381bd7 becomes ae8c799828381bd7, 
- 15d76d8d8fbfa76f becomes f5d76d8d8fbfa76f and 
- 155a376f265097d6 becomes b55a376f265097d6

**Comment by nosklo** [comment]
Ok, version 3 of the shaderutils can unpack shaders. Just unpack and remove the ones you want.
