### ISSUE TITLE
Graphics pack detection simplification

### ISSUE THREAD

**Issue by Wolf-lbh** [nosklo/cemu_utils#2]
Firstly, I'm pretty sure requesting features doesn't go here but I don't see any place to contact you about requesting new features so I'm sorry this is in the wrong place. Anyways on to the request:

Could you make an option, say in the res file to put "allgames" and have the updater install graphics packs for every game even if they are not installed on the host system yet? I don't want to have to worry about it not detecting an installed game or having to run the tool every time I install a new game and that would make my life so much easier.

Also I'm pretty sure this is a big request but is there any way it could detect the version of cemu you are on and update cemu itself without deleting your settings, config files, or saves? Even if all it did was move the files from a folder like cemu\update without deleting settings, configs, and saves that would be a huge improvement over the current cemu update process.

Thanks for the awesome program.

**Comment by nosklo** [comment]
Hi, thank you for sending your suggestions. I'm glad the tool is useful.

> have the updater install graphics packs for every game even if they are not installed on the host system yet

Sure, that is already possible, edit the file `upd_cemu.json`, and remove every game from `gameid_list`. Leaving that list empty (`[]`) will unpack the packs for all games. Also set `update_gameid_list` to `false` to stop it from detecting your games.

```
   "gameid_list": [],
   "update_gameid_list": false,
```

About cemu automatic updates, that could break some games since cemu is experimental, so I have no plans into adding that for now. I can see it happening, in a tool capable of using the correct best cemu version for each game...
