### ISSUE TITLE
Game .rpx file association to upd in 1.15.5 opens 1.11.4

### ISSUE THREAD

**Issue by CyberWolf755** [nosklo/cemu_utils#6]
Set up the tool for CEMU 1.11.4 and it worked without issues (that I know of), but since I saw that CEMU 1.11.5 got released a few days ago i downloaded it and set it up.
I changed the .rpx file to use upd_cemu.exe in the 1.11.5 folder but it opened CEMU 1.11.4 even though the path in the .json file is going to CEMU 1.11.5 folder
`{
    "cemu_path": "D:\\Games\\CEMU\\cemu_1.11.4",
    "download_dir": "D:\\Games\\CEMU\\cemu_1.11.4",
    "delete_downloads": true,
    "resolution_file": "D:\\Games\\CEMU\\cemu_1.11.4\\res.txt",
    "resolutions": [
        [
            1920,
            1080
        ],
        [
            1280,
            720
        ]
    ],
    "last_graphic_packs": "graphicPacks_2-786.zip",
    "last_cemuhook": null,
    "keep_dir": "D:\\Games\\CEMU\\cemu_1.11.4\\vault",
    "gameid_list": [
        "00050000101C9500"
    ],
    "exec_cemu": true,
    "extra_params": [],
    "fullscreen": true,
    "update_gameid_list": true
}`

**Comment by nosklo** [comment]
Hi, thanks for your report. Since you changed the folder name for this version, you will have to change all the paths in the configuration file. However in your case it seems you didn't change anything yourself, so you can just delete the `upd_cemu.json` file and it will be generated again with the correct paths and work fine.
